version : '3.7'
services:
  db:
    image: surrealdb/surrealdb:latest
    restart: always
    command: start --user root --pass root memory
    ports:
      - '8000:8000'
    volumes:
      - db:/var/lib/surrealdb/data
    networks:
      - backend

  rest-api:
    image: be-rust
    ports:
      - "8088:8088"
    networks:
      - backend
    depends_on:
      - db
    environment:
      - BASE_URL=http://172.24.0.2:8000
      - CORS_ALLOW=http://website:8080

  website:
    build: .
    image: perseus-website
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - rest-api
    environment:
      - REST_URL=172.24.0.3
      - REST_PORT=8088
      - PERSEUS_HOST=0.0.0.0

networks:
  backend:

volumes:
  db:
    driver: local
